[env]
TERM = "xterm-256color"

[window]
title = "alacritty"
position = { x = 0, y = 0 }
dimensions = { columns = 200, lines = 64 }
resize_increments = true
padding = { x = 10, y  = 10 }
opacity = 1.0
startup_mode = "Windowed"
decorations = "Full"
option_as_alt = "Both"

[font]
size = 14
normal = { family = "MonaspiceAr Nerd Font", style = "Regular" }
bold = { family = "MonaspiceAr Nerd Font", style = "Bold" }
italic = { family = "MonaspiceAr Nerd Font", style = "Italic" }
bold_italic = { family = "MonaspiceAr Nerd Font", style = "Bold Italic" }
offset = { x = 0, y = 1 }

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Beam"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[keyboard]
bindings = [
  { key = "F5", action = "ToggleSimpleFullScreen" },
]
