[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y  = 10 }
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Maximized"

[font]
size = 14
normal = { family = "MonaspiceAr Nerd Font", style = "Regular" }
bold = { family = "MonaspiceAr Nerd Font", style = "Bold" }
italic = { family = "MonaspiceAr Nerd Font", style = "Italic" }
bold_italic = { family = "MonaspiceAr Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Beam"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]
